from .schemas import (
    AspectRatio,
    ImageSize,
    StyleHint,
    ChatMessage,
    GenerateRequest,
    ChatRequest,
    ImageAnalyzeRequest,
    ImageGenerateRequest,
    SimilarSearchRequest,
    AnalysisResult,
    ImageAnalysis,
    ElementItem,
    ElementsGroup,
    StyleInfo,
    PhysicalSpecs,
    SimilarItem,
    GenerationResult,
    ChatResponse,
    DesignResponse,
    ErrorResponse,
    # 新增：产品类型和结构类型枚举
    ProductType,
    StructureType,
    # 新增：分层Prompt模型
    PromptLayer,
    LayeredPrompt,
    # 新增：预设模型
    ColorPalette,
    ProductTypePreset,
    StylePreset,
    DesignPreset,
    PresetListResponse,
    # 新增：增强版请求响应
    GenerateRequestV2,
    DesignResponseV2,
)

__all__ = [
    "AspectRatio",
    "ImageSize",
    "StyleHint",
    "ChatMessage",
    "GenerateRequest",
    "ChatRequest",
    "ImageAnalyzeRequest",
    "ImageGenerateRequest",
    "SimilarSearchRequest",
    "AnalysisResult",
    "ImageAnalysis",
    "ElementItem",
    "ElementsGroup",
    "StyleInfo",
    "PhysicalSpecs",
    "SimilarItem",
    "GenerationResult",
    "ChatResponse",
    "DesignResponse",
    "ErrorResponse",
    # 新增
    "ProductType",
    "StructureType",
    "PromptLayer",
    "LayeredPrompt",
    "ColorPalette",
    "ProductTypePreset",
    "StylePreset",
    "DesignPreset",
    "PresetListResponse",
    "GenerateRequestV2",
    "DesignResponseV2",
]
